feat(FHS): add slides and lab Dockerfile
k8s-gt/linux-cli-essentials pull request #1
Opened 2022-11-29 04:15 UTC by mvlsqz

2023-02-07 03:09 UTC, jossemarGT requested changes
Hola @mvlsqz ¡tu presentación quedó genial! 

Solo podrías hacer lo siguiente para seguir con el merge:

- Mover todos los assets generados al directorio `docs/` (creo que esto incluye a todos los archivos en le PR menos el `README.md`). De esta manera podemos servirlo como GH page
- En el directorio `03-linux-filesystem-tree` dejar el README.md. En caso este se usa para renderizar los slides entonces duplicarlo.
- Como extra ¿podrías considerar remover las imágenes que no son utilizadas?

Si gustas podemos seguir conversando fuera del review thread para encontrar opciones.

2023-03-08 04:22 UTC, mvlsqz commented
hola @jossemarGT podrias por favor revisar si la estructura de archivos es la solicitada? Gracias

2023-03-16 00:37 UTC, jossemarGT commented
Hey @mvlsqz muchas gracias, solo podrías mover el directorio `/docs` a la raíz del repositorio?

2023-03-16 22:44 UTC, jossemarGT approved these changes
I think the `docs` directory needs to be in the project root, but I'll take care of it 👍

2023-03-16 22:45 UTC, merged